services:
  tasker-postgres:
    image: postgres:15
    container_name: tasker-postgres
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: tasker
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - tasker-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  tasker-postgres-data: