spring.application.name=task.er
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:54321/tasker}
spring.datasource.username=${DATASOURCE_USERNAME:root}
spring.datasource.password=${DATASOURCE_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api
